---
- name: Delete webservers, nfsservers
  hosts: webservers, nfs_servers
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark
      package:
        name: wireshark
        state: removed
        
- name: Delete loadbalancer server
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      package:
        name: wireshark-qt
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes